### ISSUE TITLE
converge.sh fails on first run if chruby has not yet been installed prior

### ISSUE THREAD

**Issue by aauthor** [luan/dotfiles#5]
When running on a new mac, the `converge.sh` script failed when it got to

```
ruby-install ruby 2.1.7 --no-reinstall
chruby ruby-2.1.7
```

I *think* you can `source /usr/local/share/chruby/chruby.sh` after you install chruby and before using it in the script, and you'll have `chruby` available.

**Comment by luan** [comment]
Done!
